# Generated by Django 5.1.3 on 2024-12-09 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClubUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First Name', models.CharField(max_length=255)),
                ('Last Name', models.CharField(max_length=255)),
                ('User Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Venue Name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('Zip Code', models.CharField(max_length=15)),
                ('Contact Phone', models.CharField(max_length=20)),
                ('Web Address', models.URLField()),
                ('Email Address', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event Name', models.CharField(max_length=120)),
                ('Event Date', models.DateTimeField()),
                ('manager', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attendees', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club_events.venue')),
            ],
        ),
    ]
