# Generated by Django 5.1.3 on 2024-12-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Event Date',
            new_name='event_date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Event Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='myclubusers',
            old_name='User Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='myclubusers',
            old_name='First Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='myclubusers',
            old_name='Last Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='Email Address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='Venue Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='Contact Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='Web Address',
            new_name='web',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='Zip Code',
            new_name='zip_code',
        ),
    ]
