# Generated by Django 5.1.3 on 2024-12-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_events', '0002_rename_event_date_event_event_date_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyClubUsers',
            new_name='MyClubUser',
        ),
    ]
