# Generated by Django 5.1.3 on 2024-12-12 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_events', '0006_event_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club_events.venue'),
            preserve_default=False,
        ),
    ]
