# Generated by Django 5.1.3 on 2024-12-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_events', '0008_venue_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyClubUser',
        ),
    ]
